function Plot_Tire_Outputs(index)
cla;

if(index>40)
    index = 40;
    disp('Plot_Tire_Inputs - index out of range');
end

Label_Title = {'Fx(N)','Longitudinal Force';...
               'Fy(N)','Lateral Force';...
               'Fz(N)','Vertical Force';...
               'Mx(Nm)','Overturning Moment';...
               'My(Nm)','Rolling Resistance';...
               'Mz(Nm)','Self-Aligning Moment';...
               'Long Slip','Longitudinal Slip';...
               'Slideslip(rad)','Sideslip Angle';...
               'Inc. Angle(rad)','Inclination Angle';...
               'Turnslip(1/m)','Turn Slip';...
               'Vx(m/s)','Contact Center Vx';...
               'x','x';...
               'Roll rad(m)','Rolling Radius';...
               'Tdefl(m)','Tire Deflection';...
               'CLength(m)','Contact Length';...
               'PneuTr(m)','Pneumatic Trail';...
               'MuLong','Longitudinal mu';...
               'MuLat','Lateral mu';...
               'RelaxLong(m)','Long. Relaxation Length';...
               'RelaxLat(m)','Lat. Relaxation Length';...
               'WSVelLong(m/s)','Long. Whl Slip Vel';...
               'WSVelLat(m/s)','Lateral. Whl Slip Vel';...
               'ComprVel(m/s)','Compression Vel.';...
               'YawVel(m/s)','Yaw Velocity';...
               'x','x';...
               'x','x';...
               'x','x';...
               'Dist(m)','Travelled Distance';...
               'x','x';...
               'x','x';...
               'xPos(m)','Contact Point x';...
               'yPos(m)','Contact Point y';...
               'zPos(m)','Contact Point z';...
               'IRNx','Road Normal x';...
               'IRNy','Road Normal y';...
               'IRNz','Road Normal z';...
               'Height(m)','Road Height';...
               'Slope(rad)','Road Slope';...
               'Curv(1/m)','Road Curvature';...
               'Bank(rad)','Road Banking'};
               
                
%annotation(gcf,'textbox',...
%    [0.285294117647059 0.904072046109507 0.456862745098039 0.103746397694524],...
%    'String',Label_Title(index,2),...
%    'HorizontalAlignment','center',...
%    'FitBoxToText','on',...
%    'FontSize',12,...
%    'FontWeight','bold',...
%    'LineStyle','none');

LineStyle = 'b';
TitleFntSz = 10;
TitleFntWt = 'normal';
subplot(221)
evalin('base',['plot(tout,varinf1(:,' num2str(index) '),''b'',''LineWidth'',2);']);
title('LF Tire   ','HorizontalAlignment','right','FontWeight',TitleFntWt,'FontSize',TitleFntSz);
%xlabel('Time (s)')
ylabel(char(Label_Title(index,1)));

subplot(222)
evalin('base',['plot(tout,varinf2(:,' num2str(index) '),''b'',''LineWidth'',2);']);
title('   RF Tire','HorizontalAlignment','left','FontWeight',TitleFntWt,'FontSize',TitleFntSz);
%xlabel('Time (s)')
%ylabel(char(Label_Title(index,1)));

subplot(223)
evalin('base',['plot(tout,varinf3(:,' num2str(index) '),''b'',''LineWidth'',2);']);
title('LR Tire   ','HorizontalAlignment','right','FontWeight',TitleFntWt,'FontSize',TitleFntSz);
xlabel('Time (s)')
ylabel(char(Label_Title(index,1)));

subplot(224)
evalin('base',['plot(tout,varinf4(:,' num2str(index) '),''b'',''LineWidth'',2);']);
title('   RR Tire','HorizontalAlignment','left','FontWeight',TitleFntWt,'FontSize',TitleFntSz);
xlabel('Time (s)')
%ylabel(char(Label_Title(index,1)));
